// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoesApp.Data;

#nullable disable

namespace ShoesApp.Migrations
{
    [DbContext(typeof(ShoesDbContext))]
    [Migration("20250818090909_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShoesApp.Models.Shoe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Shoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Nike",
                            Category = "Running",
                            Color = "Black/White",
                            ImageUrl = "/images/shoes/nike-airmax270.jpg",
                            Model = "Air Max 270",
                            Price = 120.99m,
                            Size = 42
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Adidas",
                            Category = "Running",
                            Color = "Core Black",
                            ImageUrl = "/images/shoes/adidas-ultraboost21.jpg",
                            Model = "Ultraboost 21",
                            Price = 150.50m,
                            Size = 43
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Puma",
                            Category = "Casual",
                            Color = "White/Blue",
                            ImageUrl = "/images/shoes/puma-rsx.jpg",
                            Model = "RS-X",
                            Price = 95.00m,
                            Size = 41
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Converse",
                            Category = "Casual",
                            Color = "Red",
                            ImageUrl = "/images/shoes/converse-chucktaylor.jpg",
                            Model = "Chuck Taylor All Star",
                            Price = 60.00m,
                            Size = 44
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Clarks",
                            Category = "Formal",
                            Color = "Brown",
                            ImageUrl = "/images/shoes/clarks-tilden.jpg",
                            Model = "Tilden Cap",
                            Price = 80.00m,
                            Size = 42
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
